urls.py
import os
#from django.conf.urls import patterns, include, url
from django.conf.urls import patterns, url, include
#from django.contrib.staticfiles.urls import staticfiles_urlpatterns #static files
# Uncomment the next two lines to enable the admin:
from django.contrib.gis import admin
admin.autodiscover()
#static files
from django.conf import settings #import settings 
from django.conf.urls.static import static #import url static
from os.path import dirname
basedir = dirname(__file__)
from django.http import HttpResponse
from community.feed import LatestEntriesFeed
#from community.views import *
#from django.conf.urls import handler404, handler500


staticFiles = os.path.join(basedir, "static")
webStaticFiles = '%s/web/static/' % basedir
media = '%s/media/' % basedir

urlpatterns = patterns('',
    #static files
    (r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root': staticFiles,'show_indexes': True}),  #static community app
    #(r'^static/web/(?P<path>.*)$','django.views.static.serve',{'document_root': webStaticFiles,'show_indexes': True}),
    (r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root': media,'show_indexes': True}),
    #end static files
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'community.views.communityEvolution'),
    url(r'^', include('web.urls')),
    url(r'^newsletter/', include('newsletter.urls')),	
    url(r'^marius/', include('mariustest.urls')),
    url(r'^communities/', include('community.urls')),
    url(r'^admin_tools/', include('admin_tools.urls')),
    (r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /media/\nDisallow: /static/\nDisallow: /admin/", mimetype="text/plain")),
    (r'^business/events/(?P<business_id>\d+)/rss/$', LatestEntriesFeed()),

) #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #url for static files django docs

#urlpatterns += staticfiles_urlpatterns() #for static files

handler404 = 'community.views.handler404'
handler500 = 'community.views.handler500'

web/models.py
import urlparse
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from localflavor.us.models import PhoneNumberField
from community.models import Community
from community.widgets import TextEditorWidget


class EditorField(models.TextField):
    def __init__(self, thumb=None, *args, **kwargs):
        self._thumb = thumb
        print self._thumb
        super(EditorField, self).__init__(*args, **kwargs)

    def formfield(self, **kwargs):
        kwargs['widget'] = TextEditorWidget
        return super(EditorField, self).formfield(**kwargs)


class RegisterUser(models.Model):
    firstname = models.CharField(max_length=48, blank=True, null=True)
    lastname = models.CharField(max_length=48, blank=True, null=True)
    address = models.CharField(max_length=72, blank=True, null=True)
    city = models.CharField(max_length=36, blank=True, null=True)
    state = models.CharField(max_length=45, blank=True, null=True)
    zip_code = models.CharField(max_length=5, blank=True)
    phone = models.CharField(max_length=12, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    cell = models.CharField(max_length=12, blank=True)
    website = models.URLField(blank=True, null=True)
    active = models.BooleanField(default=False)
    suscribe = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Form Register User'
        verbose_name_plural = 'Form Register User'

    def __unicode__(self):
        return '%s %s' % (self.firstname, self.lastname)


class RegisterBusiness(models.Model):
    name = models.CharField(max_length=48)
    address = models.CharField(max_length=72)
    city = models.CharField(max_length=36)
    state = models.CharField(max_length=45, blank=True, null=True)
    owner = models.CharField(max_length=36)
    zip_code = models.CharField(max_length=5, blank=True)
    contact = models.CharField(max_length=36)
    phone = models.CharField(max_length=12)
    email = models.EmailField()
    cell = models.CharField(max_length=12, blank=True)
    website = models.URLField(blank=True)
    active = models.BooleanField(default=False)
    id_biz = models.IntegerField(max_length=12, blank=True)

    class Meta:
        verbose_name = 'Form Register Business'
        verbose_name_plural = 'Form Register Businesses'

    def __unicode__(self):
        return '%s' % self.name

    def urlbusines_admin(self):
        if self.id_biz:
            return u'<a href="/admin/community/business/%s/">/admin/community/business/%s/</a>' % (
                self.id_biz, self.id_biz)
        else:
            return u'<p>None Business</p>'

    urlbusines_admin.allow_tags = True
    urlbusines_admin.short_description = 'URL Business'


class CategoryRegisterBusiness(models.Model):
    id_cat = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=36, blank=True, null=True)
    register_business = models.ForeignKey(RegisterBusiness, blank=True, null=True)

    class Meta:
        verbose_name = 'Category for Register Business'
        verbose_name_plural = 'Category for Register Businesses'

    def __unicode__(self):
        return '%s' % self.name


class MarketingTypes(models.Model):
    name = models.CharField(max_length=45, blank=True, null=True)
    register_business = models.ForeignKey(RegisterBusiness, blank=True, null=True)

    class Meta:
        verbose_name = 'Marketing Types for Register Business'
        verbose_name_plural = 'Marketing for Register Businesses'

    def __unicode__(self):
        return '%s' % self.name


class MarketingTactics(models.Model):
    name = models.CharField(max_length=45, blank=True, null=True)
    register_business = models.ForeignKey(RegisterBusiness, blank=True, null=True)

    class Meta:
        verbose_name = 'Marketing Tactics for Register Business'
        verbose_name_plural = 'Marketing Tactics for Register Businesses'

    def __unicode__(self):
        return '%s' % self.name


class ConductMarketing(models.Model):
    name = models.CharField(max_length=45, blank=True, null=True)
    register_business = models.ForeignKey(RegisterBusiness, blank=True, null=True)

    class Meta:
        verbose_name = 'Conduct Marketing for Register Business'
        verbose_name_plural = 'Conduct Marketing for Register Businesses'

    def __unicode__(self):
        return '%s' % self.name


class FrecuencyMarketing(models.Model):
    name = models.CharField(max_length=45, blank=True, null=True)
    register_business = models.ForeignKey(RegisterBusiness, blank=True, null=True)

    class Meta:
        verbose_name = 'Frecuency Marketing for Register Business'
        verbose_name_plural = 'Frecuency Marketing for Register Businesses'

    def __unicode__(self):
        return '%s' % self.name


class MonthMarketing(models.Model):
    name = models.CharField(max_length=45, blank=True, null=True)
    register_business = models.ForeignKey(RegisterBusiness, blank=True, null=True)

    class Meta:
        verbose_name = 'Month Marketing for Register Business'
        verbose_name_plural = 'Month Marketing for Register Businesses'

    def __unicode__(self):
        return '%s' % self.name


class EmailUs(models.Model):
    CHOICES_INTERESTED = (
        ('FA', 'Free Advertising'),
        ('DA', 'DetourMaps Advertising'),
        ('SC', '$10 Savings Card'),
        ('GW', 'Graphic & Web'),
        ('MT', 'Mobile Text'),
        ('SM', 'Social Media'),
        ('EB', 'Email Blast'),
        ('CP', 'Create Promotions'),
        ('PV', 'Photo & Video'),
        ('SG', 'Suggestions')
    )
    interested = models.CharField(max_length=2, choices=CHOICES_INTERESTED)
    name_is = models.CharField(max_length=48)
    email_is = models.EmailField()
    phones_is = models.CharField(max_length=12)
    questions = models.TextField(blank=True)

    class Meta:
        verbose_name = 'Form Email us'
        verbose_name_plural = 'Form Email us'

    def __unicode__(self):
        return '%s, %s' % (self.get_interested_display(), self.name_is)


class CouponRequestsForm(models.Model):
    name = models.CharField(max_length=60)
    cellphone = PhoneNumberField()
    email = models.EmailField()
    community = models.ForeignKey(Community, null=True)
    subscribe = models.BooleanField()

    def __unicode__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = 'Form Coupon Request'
        verbose_name_plural = 'Form Coupon Request'


class Module(models.Model):
    CHOICES_TEMPLATES = (
        ('H', 'Home'),
        ('A', 'About Us'),
        ('C', 'Communities'),
        ('D', 'Deals'),
        ('R', 'Free Business listing'),
        ('P', 'Printed Maps'),
        ('I', 'Interactive Maps'),
        ('E', 'Contact'),
        ('K', 'Carrier'),
        ('L', 'Landing Pages'),
    )
    CHOICES_TYPE_MODULES = (
        ('B', 'BlockHome'),
        ('T', 'SimpleText'),
        ('C', 'ComplexText'),
        ('M', 'Testimonial'),
        ('H', 'Header'),
        ('D', 'Detail'),
        ('P', 'Purchase'),
        ('L', 'LandingText'),
        ('V', 'Video')
    )
    page = models.CharField(max_length=1, choices=CHOICES_TEMPLATES)
    type_module = models.CharField(max_length=1, choices=CHOICES_TYPE_MODULES, verbose_name='Module Type')
    quantum = models.IntegerField(max_length=1, blank=True)

    def __unicode__(self):
        return '%s, %s' % (self.get_type_module_display(), self.get_page_display())


class Page(models.Model):
    CHOICES_TEMPLATES = (
        ('H', 'Home'),
        ('A', 'About Us'),
        ('C', 'Communities'),
        ('D', 'Deals'),
        ('R', 'Free Business listing'),
        ('P', 'Printed Maps'),
        ('I', 'Interactive Maps'),
        ('E', 'Contact'),
        ('K', 'Carrier'),
        ('L', 'Landing Pages'),
    )
    name = models.CharField(max_length=24)
    url_name = models.SlugField(verbose_name='URL name', blank=True)
    is_a_root = models.BooleanField(default=False, help_text='Mark if a page is Page Home')
    published = models.BooleanField(default=False, help_text='Mark to publish')
    is_menu = models.BooleanField(default=False, verbose_name='Is a Menu?', help_text='Mark if is a principal menu')
    title = models.SlugField(blank=True)
    keywords = models.TextField(help_text='Insert words separated by commas', blank=True)
    description = models.TextField(help_text='Insert phrases that describe the page', blank=True)
    template = models.CharField(max_length=1, choices=CHOICES_TEMPLATES)

    def EditContent(self):
        link = "<a href='/admin/web/page/%s'>Edit Content</a>" % self.id
        return link

    EditContent.short_description = 'Add Content'
    EditContent.allow_tags = True

    def CMS(self):
        module_obejct = Module.objects.filter(page=self.template)
        linky = "<div>Modules"
        header = ""
        for i in module_obejct:
            linky += '<div><a href="/content/?idm=%s&idp=%s" id="%s" class="addLink" style="margin-left:8px;">Add %s</a></div>' % (
                i.type_module, self.pk, i.id, i.get_type_module_display())
        linky += "</div>"
        return linky

    CMS.short_description = 'Modules to add'
    CMS.allow_tags = True

    def HeaderBlock(self):
        header_object = Header.objects.filter(page__id=self.id)
        headers = ""
        if header_object:
            for i in header_object:
                headers += "<div><div>%s</div><div><img src='/media/%s'/></div></div>" % (i.title, i.image)
        else:
            headers = "<div>Template without Header</div>"
        return headers

    HeaderBlock.short_description = "Headers"
    HeaderBlock.allow_tags = True

    def TextBlock(self):
        block_object = BlockHome.objects.filter(page=self)
        blocker = ""
        if block_object:
            for i in block_object:
                if i.has_image:

web/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <title>DetourMaps - {% block title %}Your advertising platform{% endblock %}</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script type="text/javascript">
        WebFontConfig = {
            google: { families: [ 'Open+Sans:400,700:latin', 'Inder::latin', 'Arvo:400,700:latin' ] }
        };
        (function() {
            var wf = document.createElement('script');
            wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
                    '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
            wf.type = 'text/javascript';
            wf.async = 'true';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(wf, s);
        })();
    </script>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
        <script src="http://code.jquery.com/ui/1.8.22/jquery-ui.min.js" type="text/javascript"></script>
        <script src="{{ STATIC_URL }}web/jquery.nivo.slider.pack.js" type="text/javascript"></script>
    <!--[if lte IE 9]><link rel="stylesheet" href="css/ie.css" type="text/css" media="screen" /><![endif]-->
    <!--[if lt IE 9]><script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <link rel="shortcut icon" href="{{ STATIC_URL }}web/detourMaps.ico">
    <link rel="stylesheet" href="{{ STATIC_URL }}web/nivo-slider.css" type="text/css" media="screen" />

    <link rel="stylesheet" href="{{ STATIC_URL }}web/css/1140.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="{{ STATIC_URL }}web/css/styles.css" type="text/css" media="screen" />
    {% block extrahead %}
    {% endblock %}
    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-31412199-1']);
        _gaq.push(['_setDomainName', 'detourmaps.com']);
        _gaq.push(['_trackPageview']);
        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
</head>
<body id="{% block bodyname %}home-page{% endblock %}">
<header class="container">
    <div class="row">
        <div class="fourcol logo">
            <a href="/"><img src="{{ STATIC_URL }}community/img/detourOrange.png" alt="DetourMaps"/></a>
        </div>
        <nav class="eightcol last">
            <ul class="">
                <li id="nav-about"><a href="{% url "render" "about-us" %}">About</a></li>
                <li id="nav-communities"><a href="{% url "community.views.communitySelection" %}">Communities</a></li>
                <li id="nav-deals"><a href="{% url "render" "deals" %}">Deals</a></li>
            </ul>
        </nav>
    </div>
    <div class="headerLine" style="position: absolute; height: 1px; width: 100%; bottom: 0; left: 0; background-color: #bbd8e7;margin-bottom: 10px;"></div>
</header>
{% block content %}

{% endblock %}
{% block contact %}
<div class="container padding"><div class="contactBackground"></div></div>
<div class="container contact">
    <ul>
        <li><span>Get in Touch</span></li>
        <li><a href="{% url "render" "free-business-listing" %}"><span class="freeListing"></span> Free Business Listing</a></li>
        <li><a href="{% url "render" "contact" %}"><span class="mail"></span> Contact Us</a></li>
        <li>
            <a href="https://www.facebook.com/detourmaps" target="_blank">
            <span class="facebook"></span> Like Us</a>
        </li>
        <li>
            <a href="https://twitter.com/detourmaps" target="_blank">
            <span class="twitter"></span> Follow Us</a>
        </li>
        <li><a href="http://www.youtube.com/user/detourmapstv?feature=watch"><span class="video"></span> Watch Us</a></li>
    </ul>
</div>
{% endblock %}
{% block footer %}
<footer class="container">
    <div class="row">
        <div class="twelvecol">
            <small>
                <a href="{% url "render" "us" %}" target="_blank"> Detour Community Maps</a>
                &copy; 2012 powered by
                <a href="http://www.entiremarketinggroup.com/" target="_blank">Entire Marketing Group LLC</a>
            </small>
        </div>
    </div>
</footer>
{% endblock %}
</body>
</html>

web/templates/bring-detourmaps.html
{% extends 'base-new.html' %}
{% block title %}Bring DetourMaps to your Neighborhood{% endblock %}
{% block head %}
    <link rel="stylesheet" type="text/css" media="screen" href="{{ STATIC_URL }}community/css/dtmfront-evolution.css">
    <link rel="stylesheet" type="text/css" media="screen" href="{{ STATIC_URL }}community/css/style_home.css">
    <link rel="stylesheet" type="text/css" media="screen" href="{{ STATIC_URL }}animation/style.css">
    <link rel="stylesheet" type="text/css" media="screen" href="{{ STATIC_URL }}web-icon/css/font-awesome.min.css">

    <link rel="stylesheet" href="{{ STATIC_URL }}custom-theme/jquery-ui-1.10.3.custom.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}modal/jquery.modal.css" type="text/css" media="screen"/>
    <!--[if lt IE 9]>
    <script src="{{ STATIC_URL }}aFarkas-html5shiv-67bff28/dist/html5shiv.js"></script>
    <![endif]-->
    <style type="text/css">
        body {
            background: #fff !important;
        }

        .overmenu {
            z-index: 1000;
        }

        footer {
            position: relative !important;
            top: 0 !important;
        }
    </style>
{% endblock %}
{% block bar-container %}{% endblock %}
{% block content %}
    <div class="container main">
        <div class="row">
            <div class="ninecol">
                <h1 class="titleBring">Engage neighbors. Connect your city. Build community.</h1>

                <div>
                    <p class="bringP">
                        Detour Maps makes it easy for your community! Now every residents and visitors knows where all
                        your main places and business<br>
                        with new promotions are located. Business, local organizations, and residents are connected with
                        neighbors to build stronger<br>
                        communities
                    </p>
                </div>
                <div id="textos">
                    <div class="uniTextos">
                        <img src="{{ STATIC_URL }}community/elementos/conect-neighbor.png"/>

                        <div>
                            <h2>Connect neighbors to build community</h2>

                            <p>
                                Detour Maps encourage residents to shop local and keep all within your community for<br>
                                better schools, parks, theaters, libraries, security with safer places to call home.
                            </p>
                        </div>
                    </div>
                    <div class="uniTextos">
                        <img src="{{ STATIC_URL }}community/elementos/save-support.png"/>

                        <div>
                            <h2>Save and get support</h2>

                            <p>
                                We will guide you with $10 Savings card around your community to save and keep the<br>
                                money within your neighborhood and support local business with smart marketing tools<br>
                                and promotions.
                            </p>
                        </div>
                    </div>
                    <div class="uniTextos">
                        <img src="{{ STATIC_URL }}community/elementos/starter.png"/>

                        <div>
                            <h2>Contact us to get started</h2>

                            <p>
                                It’s free, easy and fexible.
                            </p>
                        </div>
                    </div>
                </div>
                <div>
                    <p class="bringP">
                        Detour Maps costs nothing and residents also can get digital integration with our mobile
                        website. Our website can give you a lot<br>
                        options to plan your entertainment with our community events, checking and place reviews with
                        your favorite places. Support you<br>
                        favorite places with reviews for a better business improving.
                    </p>
                </div>
                <h2 class="titleSecondBring">Neighborhoods using Detour Maps become more connected, and their
                    development progress is contagious.</h2>

                <div id="bringPanel">
                    <form id="bringForm">
                        <h2>Bring DetourMaps to your neighborhood</h2>

                        <p>
                            If you are head on a local organization, public ofcial or a visionary entrepreneur to bring
                            Detour<br>
                            Maps to your neighborhood, please let us know, and our team will be in touch soon to help
                            you get<br>
                            started.
                        </p>

                        <h3>Your Info</h3>

                        <div class="itemFormBring"><input type="text" name="your-name" placeholder="Your Name"/></div>
                        <div class="itemFormBring"><input type="text" name="job-title" placeholder="Job Title"/></div>
                        <div class="itemFormBring"><input type="text" name="email-address" placeholder="Email Address"/>
                        </div>
                        <div class="itemFormBring"><input type="text" name="phone-number" placeholder="Phone Number"/>
                        </div>
                        <div class="itemFormBring"><input type="text" name="city" placeholder="City"/></div>
                        <div class="itemFormBring"><input type="text" name="state" placeholder="State"/></div>
                        <h3>More Info</h3>

                        <div class="itemAnchorBring"><input type="text" name="hear-us"
                                                            placeholder="How did you hear about Detourmaps?"/></div>
                        <div class="itemAnchorBring"><input type="text" name="anything-else"
                                                            placeholder="Anything else we sould know?"/></div>
                        <div class="bbar">
                            <button class="requestBtn">
                                Request Detour Maps for my Neighborhood
                            </button>
                            <button class="closeBtn">
                                Close
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="threecol last">
                <img src="{{ STATIC_URL }}community/elementos/new-isotipo.png" class="newImg"/>
            </div>
        </div>
    </div>
{% endblock %}

web/templates/content.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Add Content</title>
    <link rel="stylesheet" href="{{ STATIC_URL }}web/css/styles.css" type="text/css" media="screen" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}web/markitup/skins/markitup/style.css" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}web/markitup/sets/default/style.css" />
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}web/markitup/jquery.markitup.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}web/markitup/sets/default/set.js"></script>
    <style type="text/css">
        label{
            width: 140px;
            display: inline-block;
            font-size: 12px;
            text-align: left !important;
        }
        input[type="text"], input[type="file"], textarea,{
            display: inline-block;
        }
        .helptext{
            font-size: 10px;
            color: #989;
        }
    </style>
    <script type="text/javascript">
        $(document).ready(function(){
            $("textarea").markItUp(mySettings);
            $(".module").live("click",function(e){
                var idm = $(this).attr("idm");
                $.post("{% url "addForm" %}",{
                    'idm': idm
                },function(data){
                    $("#forms").html('<form enctype="multipart/form-data" class="form"></form>');
                    $(".form").html(data);
                    $(".form").append("<button class='btnSave'>Save Content</button>");
                })
                e.returnValue = false;
                return false;
            });
        });
    </script>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="twelvecol">
            <div style="padding: 20px; font-size: 0.65em;">
            <h2>Edit content to {{ page.get_template_display }}</h2>
            {% for module in modules %}
                {% if not forloop.last %}
                    <a href="#" id="module{{ module.pk }}" class="module" idm="{{ module.type_module }}">Add {{ module.get_type_module_display }}</a><span>&nbsp;</span><span>|</span><span>&nbsp;</span>
                {% else %}
                    <a href="#" id="module{{ module.pk }}" class="module" idm="{{ module.type_module }}">Add {{ module.get_type_module_display }}</a>
                {% endif %}
            {% endfor %}
            </div>
            <div id="forms" style="padding: 80px; font-size: 0.65em;margin-bottom: 20px; width: 600px;">

            </div>
            <hr>
            <div>
                {% for i in cantidad %}
                   <div style="padding: 80px; margin-bottom: 20px; width: 600px;">
                       <form enctype="multipart/form-data" action="" method="post">
                       {{ i }}
                           <button class="btnSendData" id="btn{{ forloop.counter }}">Edit and Save</button>
                       </form>
                   </div>
                    <hr>
                {% endfor %}
            </div>

            <input type="hidden" value="{{ page.pk }}"/>
        </div>
    </div>
</div>
</body>
</html>

web/templates/drag-marklet-m.html
{% extends "base-mobile.html" %}
<title>{% block title %}DetourMaps - Bookmarklet{% endblock %}</title>
{% block extrahead %}
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <link rel="icon" href="{{ STATIC_URL }}community/elementos/ico-detour.png"/>
    <link rel="shortcut icon" href="{{ STATIC_URL }}web/detourMaps.ico" />
    <link rel="apple-touch-icon" href="{{ STATIC_URL }}community/elementos/ico-detour.png"/>
    <link rel="apple-touch-icon-precomposed" href="{{ STATIC_URL }}community/elementos/ico-detour.png"/>
    <style>
        #detourmaps-search form{
            width: 86% !important;
            margin-left: -45% !important;
        }
    </style>
{% endblock %}
{% block body %}
    <section>
        <div id="drop">
            <a data-role="button" id="dragmarklet" href="javascript:(function(){if(window.myBookmarklet!==undefined){myBookmarklet();}else{document.body.appendChild(document.createElement('script')).src='http://detourmaps.com/static/community/js/ddmapslet.js';}})();">Share Your URL</a>
            <div id="help">←Drag this link to your Bookmarks Bar</div>
        </div>
    </section>
    <section id="chat">
        <section id="big-orange">
            <p>
                Let's Chat.
                <span>We'd love to hear about your project</span>
            <ul id="social-links">
                <li><a href=""><img src="{{ STATIC_URL }}community/elementos/face-mobile.png"/></a></li>
                <li><a href=""><img src="{{ STATIC_URL }}community/elementos/twitter-mobile.png"/></a></li>
            </ul>
            <br>
            <span>Email: <a href="mailto:info@detourmaps.com">info@detourmaps.com</a></span><br>
            <span>Telephone: <a href="tel:708-484-1119">708-484-1119</a></span><br>
            <span>Fax: 708-484-1101</span><br>
            <span>Location: 6900 W Cermak Rd. Berwyn, IL 60402</span>
            </p>
        </section>
    </section>
{% endblock %}

web/templates/media-kit-file.html
{% extends 'communityHomeB.html' %}
    <title>{% block title %}DetourMaps - Media Kit File{% endblock %}</title>
    {% block head %}
    <link rel="stylesheet" type="text/css"
          href="http://fonts.googleapis.com/css?family=Arvo:400,700|Istok+Web:400,700|Metrophobic!Open+Sans|Open+Sans+Condensed:300">
    <link rel="stylesheet" type="text/css" media="screen" href="{{ STATIC_URL }}community/css/dtmfront.css">
    <link rel="stylesheet" type="text/css" media="screen" href="{{ STATIC_URL }}community/css/style_home.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}web/js/jquery.validate.min.js"></script>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}community/js/richmarker.js"></script>
    <script defer type="text/javascript" src="{{ STATIC_URL }}community/js/utils.js"></script>
    <script defer type="text/javascript" src="/user/js/utils_sys"></script>
    <script src="{{ STATIC_URL }}community/js/layout.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}web/js/jquery.media.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}web/js/jquery.metadata.js"></script>
    <style type="text/css">
        body {
            background: #ffffff !important;
        }

        footer {
            position: relative !important;
            top: 0 !important;
            margin-top: 180px;
        }

        input:focus {
            background-color: #ffffff;
        }

        .overmenu {
            z-index: 10000;
        }

        .menuJoin li {
            width: 100%;
        }

        .menuJoin li a {
            text-align: left !important;
        }
        .media{
            position: relative;
            margin: auto;
        }
    </style>
    <script type="text/javascript">
        $(document).ready(function(){
            $('a.media').media({width:1200, height:780});
        });
    </script>
{% endblock %}
{% block bodyname %}media-kit-file{% endblock %}
{% block bar-container %}{% endblock %}
{% block content %}
    <a class="media" href="http://detourmaps.com/media/media-kit.pdf" style="position: relative; margin: auto; display: block;">Media Kit</a>
    <!--<iframe src="http://docs.google.com/viewer?url=http%3A%2F%2Fdetourmaps.com%2Fmedia%2Fmedia-kit.pdf&embedded=true" width="100%" height="780" style="border: none;"></iframe>-->
{% endblock %}